### ISSUE TITLE
[VERSION TRACK] v5.0.0 Known Issues & Bugs

### ISSUE THREAD

**Issue by jtsage** [FSGModding/FSG_Mod_Assistant#258]
# Known Bugs - v5.0.0
This issue is an umbrella issue to keep track of bugs in the current version.  You can reply directly here, but opening a new issue would make life easier for us.

## Issue List

**Comment by jtsage** [comment]
`game_enabled_##` setting does not properly toggle.

**Comment by vitalii2011** [comment]
On startup (v5.0.1(?)), tooltips are shown even if disabled in Settings:
![0010](https://github.com/user-attachments/assets/09e5644c-aef8-4c73-bfff-35cf22b7d598)
![0011](https://github.com/user-attachments/assets/056fb5d2-6dc7-4d0a-80c8-096f6234e530)

**Comment by jtsage** [comment]
> On startup (v5.0.1(?)), tooltips are shown even if disabled in Settings: ![0010](https://private-user-images.githubusercontent.com/41552153/373939496-09e5644c-aef8-4c73-bfff-35cf22b7d598.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMzE1NjgsIm5iZiI6MTcyODIzMTI2OCwicGF0aCI6Ii80MTU1MjE1My8zNzM5Mzk0OTYtMDllNTY0NGMtYWVmOC00YzczLWJmZmYtMzVjZjIyYjdkNTk4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDE2MTQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkMTFlNDFjMzliZGI0YTI2OWQ4Y2ZmZjAyYzI5YzA3ODk4YTVkMWZhY2U3YjJkOWVhYTQwNWM2NTA1ZWRiNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.V71698jMtKsZuLr5fAYC3n7Uq1U5rxNkTqhwhsbq6eg) ![0011](https://private-user-images.githubusercontent.com/41552153/373939497-056fb5d2-6dc7-4d0a-80c8-096f6234e530.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMzE1NjgsIm5iZiI6MTcyODIzMTI2OCwicGF0aCI6Ii80MTU1MjE1My8zNzM5Mzk0OTctMDU2ZmI1ZDItNmRjNy00ZDBhLTgwYzgtMDk2ZjYyMzRlNTMwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDE2MTQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxNGFmYzg4YjgxNDZlNmQwN2E3ZmUwY2QwZGIyYzIyZjI5NTFjN2VjOGMzMzE0ZGViNGQ2Yjk2YjYzOTU2ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.doq-QFTjyo0bqooeGj7JeAWzwgP23bGU5gzqRkC8OUo) Fixed: On-Off in Settings.

huh.  how about that.  as it happens, that setting doesn't do anything anymore - when I refactored to drop the bootstrap tooltips in favor of the native tooltips (which don't have the "I'm never going to disappear" problem), I forgot to add the check if they were supposed to show.  will be fixed in 5.0.2 or 5.1.0, depending on which number I use (working on implementing #259, that'll make the decision)

**Comment by carriganjosh** [comment]
Using the select all or Ctrl+A key doesn't activate the "Move To...", "Copy To..." or "Delete..." button.  To activate them you need to select/un-select a mod in the list.
All selected with Ctrl+A:
![image](https://github.com/user-attachments/assets/1045a9c9-e3e8-4967-844d-eae7474b9e59)
First mod un-selected:
![image](https://github.com/user-attachments/assets/78bed47e-874c-412a-b545-584c5fd06d96)

**Comment by jtsage** [comment]
> Using the select all or Ctrl+A key doesn't activate the "Move To...", "Copy To..." or "Delete..." button. To activate them you need to select/un-select a mod in the list. All selected with Ctrl+A: 


gross.  thanks for the report, I'll get that fixed soon.

**Comment by carriganjosh** [comment]
Also, the "Copy Favorites To..." button doesn't actually copy the mods from the folder I have marked as "Favorite Collection":
![image](https://github.com/user-attachments/assets/1062e7a0-dc26-4b36-80ab-f591d8d2674c)
![image](https://github.com/user-attachments/assets/712542f0-9da8-4598-9a48-ec6a45e1e1c0)
![image](https://github.com/user-attachments/assets/c60ca850-29e9-4e97-87d5-33cb676f4bd6)
![image](https://github.com/user-attachments/assets/be0c0ff6-ee27-45fe-b3e8-52666de0a40f)

**Comment by carriganjosh** [comment]
Resolving Version Difference hangs on "Processing Mods" dialog.  I've left it for almost 30 minutes to test.  If you close out of the program & reopen, the version difference has been fixed.
![Screenshot 2024-10-22 093244](https://github.com/user-attachments/assets/7893ee9d-67ff-493c-8214-85ef7b6690a9)
![Screenshot 2024-10-22 093353](https://github.com/user-attachments/assets/2a97fdb3-2397-4d44-8344-3ff058439677)
![Screenshot 2024-10-22 093413](https://github.com/user-attachments/assets/d0b2b6cf-27ce-4c49-87cf-598df157c228)

**Comment by jtsage** [comment]
Seemed the best place for this info - dear community translators (@vitalii2011 particularly since this is the only place I know to message you) - 

The crowdin is gonna get a little funky for a few days, as I am working 2 branches - the couple of point updates to make sure FS25 at least functions in the 5.x branch, and the parser re-write for the 6.x branch - so I'm probably just gonna hold the new strings in the 5.x branch and rely on machine translation until I can pull those over into the new one in a few days - figure middle of the week or so.

**Comment by vitalii2011** [comment]
> Seemed the best place for this info …

OK

**Comment by Dylan-M** [comment]
Just as a heads up, the Copy Favorite's button doesn't do "nothing", it actually copies FS22 favorites when you have FS25 selected and a valid FS25 favorites folder. See attached screenshots. First one shows I have FS25 selected, and a Favorites folder created and enabled. Second one shows same list of folders (So, FS25), but shows F22 mods to copy.

![Image](https://github.com/user-attachments/assets/d983e926-c6e3-4b79-a81d-d9c0162ea605)

![Image](https://github.com/user-attachments/assets/7f681289-894a-42ed-8094-481da9b98538)

**Comment by Dylan-M** [comment]
@jtsage I guess the above is actually V6 Beta 6, I forgot you were still using V5 numbers for the betas.

EDIT: I just downloaded the latest beta, and the same issue still persists. Ugh.
